CREATE DATABASE CSDL
GO

USE CSDL
GO

------------------------------

-- CREATE TABLE

CREATE TABLE USERS 
(
	ID CHAR(100) PRIMARY KEY,
	AVARTAR IMAGE,
	USERNAME NVARCHAR(100),
	EMAIL NVARCHAR(100),
	PHONE CHAR(10),
	USER_PASSWORD NVARCHAR(100),
	ACCESS NVARCHAR(50),
	CHECK (PHONE LIKE '[0-9]*10'),
	CHECK (USERNAME NOT LIKE '%[! ”%#$&”()*+,-./:;<=>?@]%')
)

CREATE TABLE ACCESS_LEVELS 
(
	ID INT PRIMARY KEY,
	LEVEL_NAME NVARCHAR(100)
)

CREATE TABLE VERTIFI_EMAIL 
(
	ID CHAR(100),
	CODE CHAR(10),
	EXPIRED_TIME TIME
)

CREATE TABLE PRODUCTS 
(
	ID CHAR(100) PRIMARY KEY,
	NAME_PD NVARCHAR(200),
	METERIAL NVARCHAR(200),
	DIMENSION NVARCHAR(200),
	IMAGE_MAIN IMAGE,
	KIND NVARCHAR(200),
	TRADEMARK NVARCHAR(200),
	DECRIPTION NVARCHAR(500),
	AMOUNT INT,
	COLOR NVARCHAR(200),
	CHECK (DIMENSION LIKE '%x%x%'),
	CHECK (AMOUNT >= 0)
)

CREATE TABLE BRAND 
(
	ID CHAR(100) PRIMARY KEY,
	NAME_BRAND VARCHAR(200),
	ORIGIN VARCHAR(200)
)

CREATE TABLE ORDERS
(
	ID CHAR(100) PRIMARY KEY,
	ID_USER CHAR(100),
	DATE_ORDER DATE,
	DATE_RECEIPT DATE,
	STATUS_ORDER VARCHAR(200),
	CHECK (STATUS_ORDER IN ('Đang giao', 'Bị hủy', 'Hoàn thành'))
)

CREATE TABLE DETAIL_ORDERS 
(
	ID CHAR(100),
	ID_PRODUCT CHAR(100),
	AMOUNT INT,
	PRICE FLOAT,
	PRIMARY KEY (ID, ID_PRODUCT),
	CHECK (AMOUNT >= 0),
	CHECK (PRICE >= 0)
)

CREATE TABLE WISH_LIST 
(
	ID_USER CHAR(100),
	ID_PRODUCT CHAR(100),
	PRIMARY KEY (ID_USER, ID_PRODUCT)
)

CREATE TABLE VOUCHERS
(
	ID_VOUCHER CHAR(100) PRIMARY KEY,
	PERCENT_DECREASE FLOAT
)

CREATE TABLE APPLY_VOUCHER
(
	ID_VOUCHER CHAR(100),
	ID_PRODUCT CHAR(100),
	PRIMARY KEY (ID_VOUCHER, ID_PRODUCT)
)

GO

-----------------------------