package Model;

public interface INameDB {
	String USERS = "USERS";
	String USER_ID = "ID";
	String USER_AVARTAR = "AVARTAR";
	String USER_USERNAME = "USERNAME";
	String USER_EMAIL = "EMAIL";
	String USER_PHONE = "PHONE";
	String USER_PASSWORD = "USER_PASSWORD";
	String USER_ACCESS = "ACCESS";

	String ACCESS_LEVELS = "ACCESS_LEVELS";

	String VERTIFI_EMAIL = "VERTIFI_EMAIL";
	String PRODUCTS = "PRODUCTS";
	// Table Products
	String PRODUCT_ID = "ID";
	String PRODUCT_ID_BRAND = "ID_BRAND";
	String PRODUCT_NAME_PD = "NAME_PD";
	String PRODUCT_METERIAL = "METERIAL";
	String PRODUCT_DIMENSION = "DIMENSION";
	String PRODUCT_IMAGE_MAIN = "IMAGE_MAIN";
	String PRODUCT_KIND = "KIND";
	String PRODUCT_TRADEMARK = "TRADEMARK";
	String PRODUCT_DECRIPTION = "DECRIPTION";
	String PRODUCT_AMOUNT = "AMOUNT";
	String PRODUCT_COLOR = "COLOR";
	String PRODUCT_PRICE = "PRICE";
	String PRODUCT_DATE_ADDED = "DATE_ADDED";

	String BRAND = "BRAND";

	String ORDERS = "ORDERS";
	String ORDER_ID = "ID";
	String ORDER_ID_USER = "ID_USER";
	String ORDER_DATE_ORDER = "DATE_ORDER";
	String ORDER_DATE_RECEIPT = "DATE_RECEIPT";
	String ORDER_STATUS_ORDER = "STATUS_ORDER";

	String DETAIL_ORDERS = "DETAIL_ORDERS";

	String WISH_LIST = "WISH_LIST";
	String WISH_LIST_ID_USER = "ID_USER";
	String WISH_LIST_ID_PRODUCT = "ID_PRODUCT";

	String VOUCHERS = "VOUCHERS";
	String VOUCHERS_ID = "ID";
	String VOUCHERS_PERCENT_DECREASE = "PERCENT_DECREASE";
	String VOUCHERS_DATE_START = "DATE_START";
	String VOUCHERS_DATE_END = "DATE_END";

	String APPLY_VOUCHER = "APPLY_VOUCHER";
	String APPLY_VOUCHER_ID = "ID";
	String APPLY_VOUCHER_ID_PRODUCT = "ID_PRODUCT";
	String APPLY_VOUCHER_CONDITION = "CONDITION";

	String CONDITION = "CONDITION";

	String MANAGEMENT_VOUCHER = "MANAGEMENT_VOUCHER";

	String CART = "CART";
	String CART_ID_USER = "ID_USER";
	String CART_ID_PRODUCT = "ID_PRODUCT";
	String CART_QUANTITY = "QUANTITY";
}
